version: '3.2'

services:
  jenkins:
    container_name: jenkins
    build:
      context: jenkins
      dockerfile: Dockerfile
      args:
        JENKINS_VERSION: 2.235
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /tmp:/var/jenkins_home/secrets/
  
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "3000:3000"
      - "222:22"
