pipeline {
    agent any
  options { timestamps () }
  stages {
        stage('Build') {
            steps {
                echo 'Building..'
		sh "python3 pyapp.py"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
